export const characters = [
    { charImg: "/assets/avatars/Icon2.png",  charName: "Lyra" },
    { charImg: "/assets/avatars/Icon3.png",  charName: "Kael" },
    { charImg: "/assets/avatars/Icon1.png",  charName: "Aeron" },
    { charImg: "/assets/avatars/Icon4.png",  charName: "Nyx" },
    { charImg: "/assets/avatars/Icon5.png",  charName: "Orin" },
    { charImg: "/assets/avatars/Icon6.png",  charName: "Zara" },
    { charImg: "/assets/avatars/Icon7.png",  charName: "Riven" },
    { charImg: "/assets/avatars/Icon8.png",  charName: "Elio" },
    { charImg: "/assets/avatars/Icon9.png",  charName: "Vexa" },
    { charImg: "/assets/avatars/Icon10.png", charName: "Thorne" },
    { charImg: "/assets/avatars/Icon11.png", charName: "Mira" },
    { charImg: "/assets/avatars/Icon12.png", charName: "Kiro" },
    { charImg: "/assets/avatars/Icon13.png", charName: "Sable" },
    { charImg: "/assets/avatars/Icon14.png", charName: "Astra" },
    { charImg: "/assets/avatars/Icon15.png", charName: "Drake" },
];
